#!/bin/bash

# Edit these to change where your tasks live
WN_CONFIG_DIRECTORY="$HOME/.whatnext"
WN_PROJECTS_DIRECTORY="$WN_CONFIG_DIRECTORY/projects"
WN_ACTIVE_DIRECTORY="$WN_CONFIG_DIRECTORY/active-tasks"
WN_CURRENT="$WN_CONFIG_DIRECTORY/current"

WN_EDITOR="${EDITOR:-nano}"

_whatnext_open() {
  local task
  task="${1:-"$WN_CURRENT"}"
  [ -a "$(realpath "$task")" ] &&
    "$WN_EDITOR" "$task"
}

_whatnext_ls() {
  if [ -n "$(ls "$WN_ACTIVE_DIRECTORY")" ]; then
    ls -A "$WN_ACTIVE_DIRECTORY"/*;
  elif [ -n "$(ls "$WN_PROJECTS_DIRECTORY")" ]; then
    ls "$WN_PROJECTS_DIRECTORY"/*;
  fi
}

_whatnext_add() {
  mkdir -p "$1"
  touch "$2"
  _whatnext_open "$2"
}

_whatnext_dispatch() {
  local cmd project task path next postponed active_project
  local project_dir task_f active_dir active_l

  # Name the parameters
  cmd="${1:-echo}"
  project="$2"
  task="$3"

  [ -h "$WN_CURRENT" ] &&
    path="$(realpath $WN_CURRENT)"

  project_dir="$WN_PROJECTS_DIRECTORY/$project"
  task_f="$project_dir/$task"

  active_dir="$WN_ACTIVE_DIRECTORY/$project"
  active_l="$active_dir/$task"

  case "$cmd" in
    add)
      _whatnext_add "$project_dir" "$task_f"
      ;;
    queue)
      [ -a "$task_f" ] ||
        _whatnext_add "$project_dir" "$task_f"
      mkdir -p "$active_dir"
      ln -nsf "$task_f" "$active_l"
      ;;
    start)
      [ -a "$active_l" ] || ( echo "That task is not in your queue" 1>&2 && return 1 )
      ln -nsf "$active_l" "$WN_CURRENT"
      _whatnext_open
      ;;
    finish)
      _whatnext_open
      active_project="$(dirname $(readlink "$WN_CURRENT" ))"
      # Hide the underlying issue
      [ -a "$path" ] &&
        mv "$path" "$(dirname "$path")/.$(basename "$path")"

      # Remove it from the active list
      rm "$(readlink "$WN_CURRENT")"
      rm $WN_CURRENT

      # Remove the project from active if no tasks are left
      rmdir --ignore-fail-on-non-empty "$active_project"

      # Print the remaining queued issues for the user to do
      # (Starting from the last project, if there are more)
      if [ -d "$active_project" ]; then
        echo "What's next?" $'\n'
        echo "$(basename "$active_project"):" $'\n'
        ls "$active_project";
      else
        echo "What's next?" $'\n'
        [ -n "$(ls "$WN_ACTIVE_DIRECTORY")" ] &&
          ls -A "$WN_ACTIVE_DIRECTORY"/*;
      fi
      ;;
    open)
      _whatnext_open
      ;;
    ls)
      _whatnext_ls
      ;;
    tree) # Requires tree to be installed, shows the whole state
      tree -a "$WN_CONFIG_DIRECTORY"
      ;;
    echo | *)
      if [ -a "$path" ]; then
        echo "$path"
        cat "$path";
      else
        echo "What's next?" $'\n'
        _whatnext_ls
      fi
  esac
}

if [ $(basename "$0") = "whatnext" ]; then
  # Ensure directories
  mkdir -p "$WN_ACTIVE_DIRECTORY"
  mkdir -p "$WN_PROJECTS_DIRECTORY"
  
  _whatnext_dispatch "$@"
fi
